name: Deploy to GitHub Pages

on:
  # Change to manual execution to test it, it's broken now :( see issue #22
  # push:
  #  branches: [main]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
          override: true

      - name: Install Trunk
        run: cargo install trunk

      - name: Install wasm-opt
        run: cargo install wasm-opt

      - name: Add WASM target
        run: rustup target add wasm32-unknown-unknown

      - name: Build (WASM)
        run: trunk build --release --public-url terrain3d --filehash false --dist docs

      - name: Optimize WASM
        run: wasm-opt -Oz -o docs/terrain3d_bg.wasm docs/terrain3d_bg.wasm

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create update branch
        id: create_branch
        run: |
          BRANCH="pages-update-$(date +'%Y%m%d%H%M%S')"
          git checkout -b $BRANCH
          git add docs/
          git commit -m "Update GitHub Pages build [skip ci]" || echo "No changes to commit"
          git push "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" HEAD:$BRANCH
          echo "branch_name=$BRANCH" >> $GITHUB_OUTPUT

      - name: Create Pull Request
        id: create_pr
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_URL=$(gh pr create --title "Update GitHub Pages build" \
            --body "Automated update from CI" \
            --base main \
            --head ${{ steps.create_branch.outputs.branch_name }} \
            --repo ${{ github.repository }} \
            --fill)
          echo "pr_url=$PR_URL" >> $GITHUB_OUTPUT

      - name: Merge Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Get PR number from the URL
          PR_NUMBER=$(basename ${{ steps.create_pr.outputs.pr_url }})
          
          # Try merging the PR
          gh pr merge $PR_NUMBER --merge --delete-branch --repo ${{ github.repository }}